<?php
!class_exists('Aif') && die('view not valid');
$web = AifView::getPath();
$url = AifRequest::getUrl('/');
$images = "$web/img";
?>
<!-- Qualification Start -->
<div class="container-fluid py-5" id="qualification">
    <div class="container">
        <div class="position-relative d-flex align-items-center justify-content-center">
            <h1 class="display-1 text-uppercase text-white" style="-webkit-text-stroke: 1px #dee2e6;">Experiencia</h1>
            <h1 class="position-absolute text-uppercase text-primary">Educación & Experiencia</h1>
        </div>
        <div class="row align-items-center">
            <div class="col-lg-6">
                <h3 class="mb-4">Estudios</h3>
                <div class="border-left border-primary pt-2 pl-4 ml-2">
                    <div class="position-relative mb-4">
                        <i class="far fa-dot-circle text-primary position-absolute" style="top: 2px; left: -32px;"></i>
                        <h5 class="font-weight-bold mb-1">Ingeniero en tecnologías de la información</h5>
                        <p class="mb-2"><strong>Universidad Tecnológica Fidel Velazquez</strong> | <small>2019 - 2021</small></p>
                        <!--<p>Tempor eos dolore amet tempor dolor tempor. Dolore ea magna sit amet dolor eirmod. Eos ipsum est tempor dolor. Clita lorem kasd sed ea lorem diam ea lorem eirmod duo sit ipsum stet lorem diam</p>-->
                    </div>
                    <div class="position-relative mb-4">
                        <i class="far fa-dot-circle text-primary position-absolute" style="top: 2px; left: -32px;"></i>
                        <h5 class="font-weight-bold mb-1">Tecnico Superior Universitario en Tecnologías de la Información y Comunicación Área Sistemas Informáticos </h5>
                        <p class="mb-2"><strong>Universidad Tecnológica Fidel Velazquez</strong> | <small>2017 - 2019</small></p>
                        <!--<p>Tempor eos dolore amet tempor dolor tempor. Dolore ea magna sit amet dolor eirmod. Eos ipsum est tempor dolor. Clita lorem kasd sed ea lorem diam ea lorem eirmod duo sit ipsum stet lorem diam</p>-->
                    </div>
                    <!--<div class="position-relative mb-4">
                            <i class="far fa-dot-circle text-primary position-absolute" style="top: 2px; left: -32px;"></i>
                            <h5 class="font-weight-bold mb-1">Master In CSE</h5>
                            <p class="mb-2"><strong>Cambridge University</strong> | <small>2000 - 2050</small></p>
                            <p>Tempor eos dolore amet tempor dolor tempor. Dolore ea magna sit amet dolor eirmod. Eos ipsum est tempor dolor. Clita lorem kasd sed ea lorem diam ea lorem eirmod duo sit ipsum stet lorem diam</p>
                        </div>-->
                </div>
            </div>
            <div class="col-lg-6">
                <h3 class="mb-4">Mi Experiencia laboral</h3>
                <div class="border-left border-primary pt-2 pl-4 ml-2">
                    <div class="position-relative mb-4">
                        <i class="far fa-dot-circle text-primary position-absolute" style="top: 2px; left: -32px;"></i>
                        <h5 class="font-weight-bold mb-1">Desarrollador Jr</h5>
                        <p class="mb-2"><strong>Anémona</strong> | <small>Enero 2022 - Febrero 2024</small></p>
                        <p>• Mantenimiento de bases de datos y registros.</p>
                        <p> • Colaboración durante el desarrollo de proyectos enfocado en la parte del Back-End empleando tecnologías como PHP, HTML, JS y MySQL para la ejecución al igual se emplearon frameworks como Laravel parte backend y Angular parte frontend.</p>
                        <p> • Resolución de problemas y atención a incidencias.</p>
                        <p> • Creación de manuales para el funcionamiento correcto de las aplicaciones. </p>

                    </div>
                    <div class="position-relative mb-4">
                        <i class="far fa-dot-circle text-primary position-absolute" style="top: 2px; left: -32px;"></i>
                        <h5 class="font-weight-bold mb-1">Desarrollador Jr</h5>
                        <p class="mb-2"><strong>Asesoría en Capacitación en Riesgos Industriales SA de CV </strong> | <small> Julio 2021 - Diciembre 2021</small></p>
                        <p>• Desarrollo de un proyecto basado en java puro.
                            • Mantenimiento de la base de datos y registros.
                            • Elaboración de documentación de código.</p>

                    </div>
                    <div class="position-relative mb-4">
                        <i class="far fa-dot-circle text-primary position-absolute" style="top: 2px; left: -32px;"></i>
                        <h5 class="font-weight-bold mb-1">Becario en sistemas</h5>
                        <p class="mb-2"><strong>Grupo Ancor </strong> | <small>Enero 2021 - Junio 2021</small></p>
                        <p>• Desarrollo de un sistema de gestión de productos en entorno web con HTML, PHP y Bootstrap.
                            • Documentación de proyectos y trabajo en equipo.
                        </p>
                    </div>
                    <div class="position-relative mb-4">
                        <i class="far fa-dot-circle text-primary position-absolute" style="top: 2px; left: -32px;"></i>
                        <h5 class="font-weight-bold mb-1">Becario en sistemas</h5>
                        <p class="mb-2"><strong>Herrajes Técnicos de México SA de CV </strong> | <small>Mayo 2019 - Noviembre 2019</small></p>
                        <p>• Resolución de problemas y atención a incidencias de código.
                            • Desarrollo de una aplicación móvil en Android para la gestión de tickets empleando java.
                            • Mantenimiento de la base de datos y registros.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Qualification End -->